require('../../bootstrap');
require('./crudTable');
require('../../ckeditor');
require('./menu');
require('./tabs');
require('./filterTable');
require('./messages');
require('./upload');
require('./localeTabs');